### ISSUE TITLE
Add Support for Logical Operators

### ISSUE THREAD

**Issue by JEbertPrime** [davidtorosyan/ti-js#13]
## Logical Operator Support

This is fairly straightforward. The syntax of logical operators in TI-BASIC is fairly standard, as in this example:

```JS
2 and 1
//evaluates to 1
1 and 0
//evaluates to 0
```
Because logical operations in TI-BASIC evaluate to a 1 (true) or 0 (false), a new return type is not needed. And, since JS already evaluates 0 as falsey and non-zero numbers as truthy, no custom logic is needed for evaluation. 

the `and`, `or` and `xor` operators can all be defined fairly easily as binary expressions. The `not(` operator will need a separate definition, I think.

**Comment by davidtorosyan** [comment]
Looks about right. One thing to consider is order of operations, for example does `2+0 and 1` resolve as `2` (which it would if the logical operator has higher precedence) or as `1` (if addition has higher precedence). 

And then there's other types. Do string expressions resolve as falsy or do they throw an error?

**Comment by JEbertPrime** [comment]
To your first question: the [wiki](http://tibasicdev.wikidot.com/nspire:and) seems to establish the logical operators beneath Math and Relational operations in order of operations, such that `1>2 and 1+1` would evaluate to `0`.
Your second question is a little harder to find an answer to; the same wiki article lists integers, Boolean expressions, Boolean lists (possibly just any list, since integers evaluate to Boolean?) and Boolean matrices. While strings can be used in certain relational operations, such as `Str1 = Str2`, it is unclear if a string alone would evaluate to a Boolean value. I'll load up a rom into an emulator and see how they're handled.

update: When a string is entered as an argument with the 'and' operator, it returns a "DATA TYPE" error.
